.pre-commit-config.yaml
This PR optimizes pre-commit speed by changing `always_run` from `true` to `false` for all hooks in `.pre-commit-config.yaml`. This allows hooks to run only on changed files locally, significantly improving development speed while maintaining complete CI coverage.
- Changed `always_run: true` to `always_run: false` for all hooks (ruff-format, ruff-check, pycodestyle, pyright)
- Changed `pass_filenames: false` to `pass_filenames: true` for ruff-format, ruff-check, and pyright hooks
- This enables file-specific execution instead of always running on the entire codebase
**Local Development:**
- Pre-commit hooks now only run on changed Python files
- Significantly faster pre-commit execution for incremental changes
- Hooks are skipped entirely when no relevant files are changed
**CI …
=> Optimize pre-commit speed by setting always_run to false

openhands/sdk/conversation/state.py
This PR addresses CodeRabbit AI feedback by removing redundant agent diff check logic in `ConversationState.create()` that duplicates functionality already present in `agent.resolve_diff_from_deserialized()`.
- **Removed redundant check**: The manual `model_dump()` comparison in `state.py` lines 122-131 was duplicating logic already implemented in `resolve_diff_from_deserialized()`
- **Simplified code**: Eliminated 10 lines of redundant code and an unnecessary import
- **Maintained functionality**: The same error behavior is preserved, but with better error messages from the dedicated method
The `resolve_diff_from_deserialized()` method already:
1. Performs the same model comparison internally (lines 104-110 in `agent/base.py`)
2. Provides more informative error messages with …
=> Remove redundant agent diff check logic

openhands/sdk/io/local.py
Fix LocalFileStore.list() to handle file targets without crashing.
- Add `os.path.isdir()` check to prevent exceptions when listing files
- Return empty list when path is a file (maintains S3-like API consistency)
- Preserves natural filesystem ordering from `os.listdir()`
Addresses CodeRabbit feedback on robustness improvements.
@enyst can click here to [continue refining the PR](https://app.all-hands.dev/conversations/d50f453285594883b98cbcfbf27db3e7)
=> Fix LocalFileStore.list() to handle file targets gracefully

openhands/sdk/event/llm_convertible.py, tests/sdk/event/test_system_prompt_event_visualize.py
The `SystemPromptEvent.visualize` method mutates the event's internal tool data by directly modifying tool dictionaries during string truncation. This causes:
1. **Data corruption**: Event tool data gets permanently truncated after first visualization
2. **Cumulative truncation**: Multiple visualizations progressively shorten already truncated data  
3. **Parameter display issues**: Long parameter JSON strings are not truncated for display
- **Prevent mutation**: Create display-only copy (`tool_display`) instead of modifying original data
- **Add parameter truncation**: Limit parameter JSON strings to 200 characters for display
- **Improve type safety**: Add `isinstance()` guard for `tool_fn` dictionary access
```python
for k, v in tool.items():
if isinstance(v, str) and len(v) > 30: …
```
=> fix: prevent data mutation during visualize

openhands/tools/task_tracker/definition.py
Improves error handling in the TaskTracker's `_load_tasks` method to be more defensive against malformed JSON.
The original code assumed `json.load(f)` would always return a list, but could fail with:
- **TypeError**: When JSON contains `null`, numbers, strings, or other non-iterable types
- **ValidationError**: When JSON contains a list with invalid task structures
Verified the fix handles all these scenarios gracefully:
```python
test_cases = [
('null', 'null'),                                    # TypeError
('string', '"not a list"'),                         # ValidationError  
('number', '42'),                                    # TypeError
('object', '{"not": "a list"}'),                    # ValidationError
('invalid_task_structure', '[{"invalid": "structure"}]'), # ValidationError …
```
=> Improve error handling in TaskTracker JSON loading

openhands/sdk/llm/llm.py, tests/sdk/llm/test_llm_json_storage.py
Add method to dump LLM to a json 
This ensures that the client doesn't need to understand how `load_from_json` works in order to serialize the LLM. The sdk should just support `LLM.load_from_json(llm.store_to_json())`
=> Add LLM JSON storage functionality

openhands/sdk/context/view.py, openhands/sdk/conversation/conversation.py, openhands/sdk/conversation/event_store.py, openhands/sdk/conversation/state.py, openhands/sdk/conversation/types.py, openhands/sdk/event/__init__.py, openhands/sdk/event/base.py, openhands/sdk/event/condenser.py, openhands/sdk/event/llm_convertible.py, openhands/sdk/event/types.py
This PR implements the proposal in #206. It also extends the logic to `Conversation` objects and `ConversationID` types, and updates some known references to these types.
=> Lift ID types in event to type aliases

.github/workflows/integration-runner.yml
This PR fixes issue #298 where the integration workflow was failing when triggered by schedule.
The integration workflow (`integration-runner.yml`) was attempting to create PR comments even when triggered by scheduled runs or manual dispatch. Since there's no actual pull request in these cases, the GitHub CLI command `gh pr comment` would fail with:
```
GraphQL: Could not resolve to a PullRequest with the number of 9745. (repository.pullRequest)
```
Added a conditional check `if: github.event_name == 'pull_request'` to the "Create consolidated PR comment" step. This ensures that PR comments are only created when the workflow is actually triggered by a pull request event.
- Modified `.github/workflows/integration-runner.yml` to conditionally execute the PR comment step only for pull …
=> Fix integration job when run on schedule

.github/workflows/server.yml
This PR fixes issue #360 by optimizing the CI workflow to only run the `build-and-push-image` job when necessary, significantly speeding up CI for most PRs.
1. **Added `build-docker` tag trigger**: Modified the workflow triggers to include the `build-docker` tag alongside the existing `main` branch trigger
2. **Added conditional logic to `build-and-push-image` job**: The job now only runs when:
- Push is to the `main` branch, OR
- Push is a tag named `build-docker`
3. **Updated `post-image-comment` job condition**: Now only runs on PRs when the build job actually ran and succeeded
- **Faster CI**: Most PRs will no longer trigger Docker builds (3 variants × 2 platforms = 6 builds), significantly reducing CI time
- **Selective builds**: Docker images are still built on main branch pushes …
=> Fix CI: Only run build-and-push-image on main or build-docker tag

openhands/agent_server/config.py, openhands/agent_server/models.py, openhands/sdk/event/condenser.py, openhands/sdk/llm/llm.py, openhands/sdk/llm/utils/telemetry.py, openhands/tools/browser_use/definition.py, openhands/tools/execute_bash/definition.py, openhands/tools/str_replace_editor/definition.py, tests/sdk/config/test_llm_config.py
- Add ge (greater than or equal) constraints to numeric fields across models
- WebhookSpec: event_buffer_size (ge=1), num_retries/retry_delay (ge=0)
- Agent models: max_iterations (ge=1), max_budget_per_task (ge=0)
- Tool definitions: timeout fields (ge=0), insert_line (ge=1), browser indices (ge=0)
- LLM parameters: temperature/top_p/top_k (ge=0), max_tokens (ge=1)
- Telemetry: cost fields (ge=0)
- Event condenser: summary_offset (ge=0)
These constraints prevent invalid negative values and ensure data integrity while maintaining backward compatibility with existing valid configurations.
=> Add gte constraints to Pydantic numeric fields

openhands/sdk/event/condenser.py, openhands/sdk/event/llm_convertible.py, openhands/sdk/tool/schema.py, openhands/tools/execute_bash/definition.py, openhands/tools/str_replace_editor/utils/diff.py, openhands/tools/task_tracker/definition.py
Newline isn't add properly for str replace editor diff visualization
It also removes all "dim" element because they looks terrible on a full black terminal background:
=> chore(visualization): remove dim everywhere, fix diff newline

openhands/sdk/llm/llm.py, tests/sdk/llm/test_llm_json_storage.py
This PR cleans up the LLM class by removing custom methods for exposing secrets during serialization and implementing the standard Pydantic context-based approach.
- **Fixed model_dump support**: Changed `when_used="json"` to `when_used="always"` to support both `model_dump()` and `model_dump_json()`
- **Removed custom method**: Eliminated `model_dump_with_secrets()` method that was creating special cases
- **Updated store_to_json**: Now uses `model_dump(context={'expose_secrets': True})` instead of custom method
- **Unified approach**: Both serialization methods now work with context-based secret exposure
- **Standard Pydantic pattern**: Uses built-in Pydantic context mechanism instead of custom methods  
- **Cleaner API**: No more special case methods - just use …
=> Remove custom model_dump_with_secrets method and use Pydantic context-based serialization

examples/04_confirmation_mode_example.py, examples/16_llm_security_analyzer.py, openhands/sdk/agent/agent.py, openhands/sdk/agent/base.py, openhands/sdk/agent/prompts/security_risk_assessment.j2, openhands/sdk/agent/prompts/system_prompt.j2, openhands/sdk/event/llm_convertible/action.py, openhands/sdk/security/risk.py, openhands/sdk/tool/tool.py, tests/sdk/agent/test_agent_immutability.py, tests/sdk/agent/test_security_policy_integration.py, tests/sdk/security/test_security_risk.py, tests/sdk/tool/test_tool.py
- Do not include the LLM risk analyzer-related system prompt when the LLM Security Analyzer is not enabled
- Fix security analyzer example with the latest confirmation policy change
- Fix to make sure `security_risk` is a required field when converting it to LLM tool
=> Fix security analyzer

.github/workflows/server.yml
This PR fixes issue #470 by replacing the noisy comment mechanism with PR description updates for agent server image information.
- **Replaced `marocchino/sticky-pull-request-comment@v2`** with `nefrob/pr-description@v1.2.0`
- **Updated job name** from `post-image-comment` to `update-pr-description` 
- **Modified the workflow** to append agent server image information to the PR description instead of creating new comments
- **Added regex pattern** to match and replace existing agent server image sections in PR descriptions
- **Reduces email notification noise** - No more comment notifications for every Docker image build
- **Cleaner PR interface** - Agent server information is part of the PR description rather than cluttering the comment section
- **Persistent information** - The agent …
=> Fix #470: Update PR description instead of creating comments for agent server images

examples/01_hello_world.py, examples/02_custom_tools.py, examples/03_activate_microagent.py, examples/04_confirmation_mode_example.py, examples/05_use_llm_registry.py, examples/06_interactive_terminal_w_reasoning.py, examples/07_mcp_integration.py, examples/08_mcp_with_oauth.py, examples/09_pause_example.py, examples/10_persistence.py, examples/11_async.py, examples/12_custom_secrets.py, examples/13_get_llm_metrics.py, examples/14_context_condenser.py, examples/15_browser_use.py, examples/18_send_message_while_processing.py, examples/19_llm_routing.py, examples/20_stuck_detector.py, examples/21_generate_extraneous_conversation_costs.py, examples/22_hello_world_with_agent_server.py, examples/23_hello_world_with_sandboxed_server.py
Example 5 (`05_use_llm_registry.py`) had a service_id mismatch that caused a KeyError:
- LLM was registered with service_id `"primary-llm"`
- But code attempted to retrieve it using `"main_agent"`
This highlighted inconsistent naming conventions across all examples.
**Fixed the immediate issue:**
- Changed example 5 to use consistent `"agent"` service_id for both registration and retrieval
**Standardized naming conventions across all examples:**
- Agent-related LLMs now use `"agent"` service_id (changed from `"main-llm"`, `"hello-world-llm"`)
- Condenser LLMs continue using `"condenser"` service_id (already correct)
- Specialized LLMs keep descriptive names (`"security-analyzer"`, `"vision-llm"`, `"multimodal-router"`)
- Multi-purpose examples use descriptive prefixes (`"agent-primary"`, …
=> Fix LLM service_id naming inconsistencies in examples

openhands/sdk/sandbox/docker.py
Prioritize Path(__file__) over Path.cwd() when resolving build.sh location. This allows the agent server sandbox to be called from other repos or different working directories without failing to find the build script.
In particular this allows to run the script from the benchmarks directory.
Changes:
- Reorder candidates list to check file-relative path first
- Update comment to reflect new priority order
---
**Agent Server images for this PR**
• **GHCR package:** https://github.com/All-Hands-AI/agent-sdk/pkgs/container/agent-server
**Variants & Base Images**
| Variant | Base Image | Docs / Tags |
|---|---|---|
| golang | `golang:1.21-bookworm` | [Link](https://hub.docker.com/_/golang:1.21-bookworm) |
| java | `eclipse-temurin:17-jdk` | …
=> Fix sandbox build script lookup to work from any directory

openhands/sdk/llm/llm.py, openhands/sdk/pyproject.toml, uv.lock
- Remove unused load_from_toml function from LLM class
- Remove tomli dependency from pyproject.toml since Python 3.12+ has built-in tomllib
- Function was not used anywhere in the codebase
- All tests pass after removal
=> Remove load_from_toml function and tomli dependency

openhands/sdk/llm/utils/model_features.py
Tiny fix for tool use enabled by default, ported from V0.
---
**Agent Server images for this PR**
• **GHCR package:** https://github.com/All-Hands-AI/agent-sdk/pkgs/container/agent-server
**Variants & Base Images**
| Variant | Base Image | Docs / Tags |
|---|---|---|
| golang | `golang:1.21-bookworm` | [Link](https://hub.docker.com/_/golang:1.21-bookworm) |
| java | `eclipse-temurin:17-jdk` | [Link](https://hub.docker.com/_/eclipse-temurin:17-jdk) |
| python | `nikolaik/python-nodejs:python3.12-nodejs22` | [Link](https://hub.docker.com/_/nikolaik/python-nodejs:python3.12-nodejs22) |
**Pull (multi-arch manifest)**
```bash
docker pull ghcr.io/all-hands-ai/agent-server:154d857-python
```
**Run**
```bash
docker run -it --rm \
-p 8000:8000 \
--name agent-server-154d857-python \ …
```
=> Fix sonnet3.5 recognition

openhands/agent_server/conversation_service.py, tests/agent_server/test_webhook_subscriber.py
Adds conversation ID support to webhook callbacks by:
- Added required `conversation_id: UUID` parameter to `WebhookSubscriber` class
- Updated webhook URL construction from `{base_url}/events` to `{base_url}/events/{conversation_id.hex}`
- Fixed all WebhookSubscriber instantiations in tests to include the new parameter
- Added `sample_conversation_id` test fixture for consistent UUID testing
- Updated test URL expectations to use dynamic conversation ID paths
This enables conversation-specific webhook callbacks
✅ All 33 tests pass
✅ Pre-commit hooks pass
✅ No breaking changes to existing functionality
=> Include conversation_id parameter in WebhookSubscriber

openhands/agent_server/conversation_router.py, openhands/agent_server/event_router.py, openhands/sdk/conversation/impl/remote_conversation.py, tests/agent_server/test_api_authentication.py
Right now, requests to some agent server endpoints require a trailing slash in order to work - without one they redirect to the endpoint with a slash. This is weird, so this PR changes the endpoints:
* `/api/conversations/` -> `/api/conversations`
* `/api/events/` -> `/api/events`
=> Have post to /conversations work without redirect

scripts/conversation_viewer.py
This PR adds two key improvements to the conversation viewer:
- Added a download button in the sidebar to export conversations as ZIP archives
- The ZIP includes  and all event files from the  directory
- Files are compressed efficiently using 
- The download is handled in-memory without creating temporary files
- Fixed a bug where the conversations directory would reset to "/" when switching between conversations
- Improved handling of Streamlit query parameters to support both old (list) and new (string) formats
- Used session state to properly persist the root directory across all page reruns
- The selected directory now remains stable throughout the entire session
- ✅ Syntax validation passed
- ✅ Download button appears in sidebar after selecting a conversation
- ✅ ZIP files are …
=> Add ZIP download for conversation visualizer and fix directory reset issue

openhands/agent_server/sockets.py, tests/agent_server/test_event_router_websocket.py
Adds optional `replay_all` parameter to the `events_socket` WebSocket endpoint.
**Changes:**
- Added `replay_all: bool = False` query parameter to `/sockets/events/{conversation_id}`
- When `replay_all=True`, fetches and sends all existing events before live subscription
- Uses pagination to handle large event histories efficiently
- Maintains backward compatibility (default behavior unchanged)
**Testing:**
- Added comprehensive test suite with 4 test cases
- All 246 agent_server tests pass
- Covers normal operation and error handling scenarios
---
**Agent Server images for this PR**
• **GHCR package:** https://github.com/All-Hands-AI/agent-sdk/pkgs/container/agent-server
**Variants & Base Images**
| Variant | Base Image | Docs / Tags |
|---|---|---|
| golang | `golang:1.21-bookworm` | …
=> Add resend_all parameter to events_socket endpoint

openhands/sdk/llm/llm.py, openhands/sdk/llm/utils/telemetry.py, tests/sdk/context/condenser/test_llm_summarizing_condenser.py, tests/sdk/llm/test_llm_pricing_passthrough.py
Addresses a few things from #637 
- LLM → Telemetry:
- forward input_cost_per_token/output_cost_per_token so that it's actually used for custom cost
- Telemetry logging: 
- de-duplicate tools (drop kwargs.tools)
- serialize raw_response with model_dump() when available
- use unique filenames with a short UUID suffix.
- Telemetry cost: 
- intentionally skip recording 0.0; added inline comment clarifying policy.
All tests pass locally (1480 passed). Larger refactors from #637 are deferred to a follow-up.
---
**Agent Server images for this PR**
• **GHCR package:** https://github.com/All-Hands-AI/agent-sdk/pkgs/container/agent-server
**Variants & Base Images**
| Variant | Base Image | Docs / Tags |
|---|---|---|
| golang | `golang:1.21-bookworm` | …
=> LLM → Telemetry: fixes
